#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

from google.protobuf.compiler import plugin_pb2 as plugin
from google.protobuf.compiler.plugin_pb2 import CodeGeneratorRequest as CodeGeneratorRequest
from google.protobuf.compiler.plugin_pb2 import CodeGeneratorResponse as CodeGeneratorResponse
from google.protobuf.descriptor_pb2 import FileDescriptorProto


class AimRTCodeGenerator(object):
    t_hfile_one_service_func: str = r"""
  virtual aimrt::co::Task<aimrt::rpc::Status> {{rpc_func_name}}(
      aimrt::rpc::ContextRef ctx_ref,
      const {{rpc_req_name}}& req,
      {{rpc_rsp_name}}& rsp);"""

    t_hfile_one_service_class: str = r"""
class {{service_name}} : public aimrt::rpc::ServiceBase {
 public:
  {{service_name}}();
  ~{{service_name}}() override = default;
{{hfile_service_func}}
};"""

    t_hfile_one_service_proxy_func: str = r"""
  aimrt::co::Task<aimrt::rpc::Status> {{rpc_func_name}}(
      aimrt::rpc::ContextRef ctx_ref,
      const {{rpc_req_name}}& req,
      {{rpc_rsp_name}}& rsp);

  aimrt::co::Task<aimrt::rpc::Status> {{rpc_func_name}}(
      const {{rpc_req_name}}& req,
      {{rpc_rsp_name}}& rsp) {
    static constexpr aimrt::rpc::ContextRef ctx_ref{};
    return {{rpc_func_name}}(ctx_ref, req, rsp);
  }"""

    t_hfile_one_service_proxy_class: str = r"""
class {{service_name}}Proxy : public aimrt::rpc::ProxyBase {
 public:
  explicit {{service_name}}Proxy(aimrt::rpc::RpcHandleRef rpc_handle_ref)
      : aimrt::rpc::ProxyBase(rpc_handle_ref) {}
  ~{{service_name}}Proxy() = default;

  static bool RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref);
{{hfile_service_proxy_func}}
};"""

    t_hfile: str = r"""/**
 * @file {{file_name}}.aimrt_rpc.pb.h
 * @brief This file was generated by protoc-gen-aimrt_rpc which is a self-defined pb compiler plugin, do not edit it!!!
 */
#pragma once

#include "aimrt_module_cpp_interface/rpc/rpc_handle.h"
#include "aimrt_module_cpp_interface/rpc/rpc_status.h"

#include "aimrt_module_cpp_interface/co/task.h"

#include "{{file_name}}.pb.h"

{{namespace_begin}}
{{hfile_service_class}}
{{hfile_service_proxy_class}}
{{namespace_end}}
"""

    t_ccfile_one_service_register_func: str = r"""
  {
    aimrt::util::Function<aimrt_function_service_func_ops_t> callback(
        [this](const aimrt_rpc_context_base_t* ctx, const void* req, void* rsp, aimrt_function_base_t* callback) {
          const aimrt::rpc::RpcHandle h =
              [this](aimrt::rpc::ContextRef ctx_ref, const void* req_ptr, void* rsp_ptr) -> aimrt::co::Task<aimrt::rpc::Status> {
            return {{rpc_func_name}}(
                ctx_ref,
                *static_cast<const {{rpc_req_name}}*>(req_ptr),
                *static_cast<{{rpc_rsp_name}}*>(rsp_ptr));
          };

          aimrt::util::Function<aimrt_function_service_callback_ops_t> f(callback);

          aimrt::co::StartDetached(
              aimrt::co::On(
                  aimrt::co::InlineScheduler(),
                  filter_mgr_.InvokeRpc(h, aimrt::rpc::ContextRef(ctx), req, rsp)) |
              aimrt::co::Then(
                  [f{std::move(f)}](aimrt::rpc::Status status) {
                    f(status.Code());
                  }));
        });
    RegisterServiceFunc(
        "pb:/{{package_name}}.{{service_name}}/{{rpc_func_name}}",
        nullptr,
        aimrt::GetProtobufMessageTypeSupport<{{rpc_req_name}}>(),
        aimrt::GetProtobufMessageTypeSupport<{{rpc_rsp_name}}>(),
        std::move(callback));
  }"""

    t_ccfile_one_service_func: str = r"""
aimrt::co::Task<aimrt::rpc::Status> {{service_name}}::{{rpc_func_name}}(
    aimrt::rpc::ContextRef ctx_ref,
    const {{rpc_req_name}}& req,
    {{rpc_rsp_name}}& rsp) {
  co_return aimrt::rpc::Status(AIMRT_RPC_STATUS_SVR_NOT_IMPLEMENTED);
}"""

    t_ccfile_one_service_class: str = r"""
{{service_name}}::{{service_name}}() {
{{ccfile_service_register_func}}
}
{{ccfile_service_func}}
"""

    t_ccfile_one_service_proxy_register_func: str = r"""
  if (!(rpc_handle_ref.RegisterClientFunc(
          "pb:/{{package_name}}.{{service_name}}/{{rpc_func_name}}",
          nullptr,
          aimrt::GetProtobufMessageTypeSupport<{{rpc_req_name}}>(),
          aimrt::GetProtobufMessageTypeSupport<{{rpc_rsp_name}}>())))
    return false;"""

    t_ccfile_one_service_proxy_func: str = r"""
aimrt::co::Task<aimrt::rpc::Status> {{service_name}}Proxy::{{rpc_func_name}}(
    aimrt::rpc::ContextRef ctx_ref,
    const {{rpc_req_name}}& req,
    {{rpc_rsp_name}}& rsp) {
  const aimrt::rpc::RpcHandle h =
      [rpc_handle_ref{rpc_handle_ref_}](aimrt::rpc::ContextRef ctx_ref, const void* req_ptr, void* rsp_ptr)
      -> aimrt::co::Task<aimrt::rpc::Status> {
    co_return co_await aimrt::co::AsyncWrapper<aimrt::rpc::Status>(
        [rpc_handle_ref, ctx_ref, req_ptr, rsp_ptr](
            aimrt::util::Function<void(aimrt::rpc::Status)>&& call_back) {
          rpc_handle_ref.Invoke(
              "pb:/{{package_name}}.{{service_name}}/{{rpc_func_name}}",
              ctx_ref, req_ptr, rsp_ptr,
              [call_back{std::move(call_back)}](uint32_t code) {
                call_back(aimrt::rpc::Status(code));
              });
        });
  };

  if (ctx_ref) {
    if (ctx_ref.GetSerializationType().empty()) ctx_ref.SetSerializationType("pb");
    co_return co_await filter_mgr_.InvokeRpc(h, ctx_ref, static_cast<const void*>(&req), static_cast<void*>(&rsp));
  }

  auto ctx_ptr = rpc_handle_ref_.NewContextSharedPtr();
  ctx_ref = aimrt::rpc::ContextRef(ctx_ptr);
  ctx_ref.SetSerializationType("pb");
  co_return co_await filter_mgr_.InvokeRpc(h, ctx_ref, static_cast<const void*>(&req), static_cast<void*>(&rsp));
}"""

    t_ccfile_one_service_proxy_class: str = r"""
bool {{service_name}}Proxy::RegisterClientFunc(aimrt::rpc::RpcHandleRef rpc_handle_ref) {
{{ccfile_service_proxy_register_func}}
  return true;
}
{{ccfile_service_proxy_func}}
"""

    t_ccfile: str = r"""/**
 * @file {{file_name}}.aimrt_rpc.pb.cc
 * @brief This file was generated by protoc-gen-aimrt_rpc which is a self-defined pb compiler plugin, do not edit it!!!
 */

#include "{{file_name}}.aimrt_rpc.pb.h"

#include "aimrt_module_cpp_interface/co/async_wrapper.h"
#include "aimrt_module_cpp_interface/co/inline_scheduler.h"
#include "aimrt_module_cpp_interface/co/on.h"
#include "aimrt_module_cpp_interface/co/start_detached.h"
#include "aimrt_module_cpp_interface/co/then.h"
#include "aimrt_module_protobuf_interface/util/protobuf_type_support.h"

#include <google/protobuf/stubs/stringpiece.h>
#include <google/protobuf/util/json_util.h>

{{namespace_begin}}
{{ccfile_service_class}}
{{ccfile_service_proxy_class}}
{{namespace_end}}
"""

    @staticmethod
    def gen_name_space_str(ns: str) -> str:
        return ns.replace(".", "::")

    @staticmethod
    def gen_namespace_begin_str(ns: str) -> str:
        namespace_vec: list[str] = ns.split(".")
        result: str = ""
        for itr in namespace_vec:
            result += "namespace " + itr + " {\n"
        return result

    @staticmethod
    def gen_namespace_end_str(ns: str) -> str:
        namespace_vec: list[str] = ns.split(".")
        result: str = ""
        for itr in namespace_vec:
            result += "}  // namespace " + itr + "\n"
        return result

    def generate(self, request: CodeGeneratorRequest) -> CodeGeneratorResponse:
        """Generate code for the given request"""
        response: CodeGeneratorResponse = CodeGeneratorResponse()
        for proto_file in request.proto_file:
            # Generate code for each file
            file_name: str = proto_file.name
            package_name: str = proto_file.package
            namespace_begin: str = self.gen_namespace_begin_str(package_name)
            namespace_end: str = self.gen_namespace_end_str(package_name)
            cc_file_name: str = file_name.replace('.proto', '.aimrt_rpc.pb.cc')
            h_file_name: str = file_name.replace('.proto', '.aimrt_rpc.pb.h')

            hfile_service_class: str = ""
            hfile_service_proxy_class: str = ""
            ccfile_service_class: str = ""
            ccfile_service_proxy_class: str = ""

            for ii in range(0, len(proto_file.service)):
                service: ServiceDescriptorProto = proto_file.service[ii]
                if ii != 0:
                    hfile_service_class += "\n"
                    hfile_service_proxy_class += "\n"
                    ccfile_service_class += "\n"
                    ccfile_service_proxy_class += "\n"

                service_name: str = service.name

                hfile_service_func: str = ""
                hfile_service_proxy_func: str = ""

                ccfile_service_register_func: str = ""
                ccfile_service_func: str = ""
                ccfile_service_proxy_register_func: str = ""
                ccfile_service_proxy_func: str = ""

                for jj in range(0, len(service.method)):
                    method: MethodDescriptorProto = service.method[jj]

                    if jj != 0:
                        hfile_service_func += "\n"
                        hfile_service_proxy_func += "\n"
                        ccfile_service_register_func += "\n"
                        ccfile_service_func += "\n"
                        ccfile_service_proxy_register_func += "\n"
                        ccfile_service_proxy_func += "\n"

                    rpc_func_name = method.name
                    rpc_req_name = self.gen_name_space_str(method.input_type)
                    rpc_rsp_name = self.gen_name_space_str(method.output_type)

                    hfile_one_service_func: str = self.t_hfile_one_service_func \
                        .replace("{{rpc_req_name}}", rpc_req_name) \
                        .replace("{{rpc_rsp_name}}", rpc_rsp_name) \
                        .replace("{{rpc_func_name}}", rpc_func_name)
                    hfile_service_func += hfile_one_service_func

                    hfile_one_service_proxy_func: str = self.t_hfile_one_service_proxy_func \
                        .replace("{{rpc_req_name}}", rpc_req_name) \
                        .replace("{{rpc_rsp_name}}", rpc_rsp_name) \
                        .replace("{{rpc_func_name}}", rpc_func_name)
                    hfile_service_proxy_func += hfile_one_service_proxy_func

                    ccfile_one_service_register_func: str = self.t_ccfile_one_service_register_func \
                        .replace("{{rpc_req_name}}", rpc_req_name) \
                        .replace("{{rpc_rsp_name}}", rpc_rsp_name) \
                        .replace("{{rpc_func_name}}", rpc_func_name)
                    ccfile_service_register_func += ccfile_one_service_register_func

                    ccfile_one_service_func: str = self.t_ccfile_one_service_func \
                        .replace("{{rpc_req_name}}", rpc_req_name) \
                        .replace("{{rpc_rsp_name}}", rpc_rsp_name) \
                        .replace("{{rpc_func_name}}", rpc_func_name)
                    ccfile_service_func += ccfile_one_service_func

                    ccfile_one_service_proxy_register_func: str = self.t_ccfile_one_service_proxy_register_func \
                        .replace("{{rpc_req_name}}", rpc_req_name) \
                        .replace("{{rpc_rsp_name}}", rpc_rsp_name) \
                        .replace("{{rpc_func_name}}", rpc_func_name)
                    ccfile_service_proxy_register_func += ccfile_one_service_proxy_register_func

                    ccfile_one_service_proxy_func: str = self.t_ccfile_one_service_proxy_func \
                        .replace("{{rpc_req_name}}", rpc_req_name) \
                        .replace("{{rpc_rsp_name}}", rpc_rsp_name) \
                        .replace("{{rpc_func_name}}", rpc_func_name)
                    ccfile_service_proxy_func += ccfile_one_service_proxy_func

                hfile_one_service_class: str = self.t_hfile_one_service_class \
                    .replace("{{hfile_service_func}}", hfile_service_func) \
                    .replace("{{service_name}}", service_name)
                hfile_service_class += hfile_one_service_class

                hfile_one_service_proxy_class: str = self.t_hfile_one_service_proxy_class \
                    .replace("{{hfile_service_proxy_func}}", hfile_service_proxy_func) \
                    .replace("{{service_name}}", service_name)
                hfile_service_proxy_class += hfile_one_service_proxy_class

                ccfile_one_service_class: str = self.t_ccfile_one_service_class \
                    .replace("{{ccfile_service_register_func}}", ccfile_service_register_func) \
                    .replace("{{ccfile_service_func}}", ccfile_service_func) \
                    .replace("{{service_name}}", service_name)
                ccfile_service_class += ccfile_one_service_class

                ccfile_one_service_proxy_class: str = self.t_ccfile_one_service_proxy_class \
                    .replace("{{ccfile_service_proxy_register_func}}", ccfile_service_proxy_register_func) \
                    .replace("{{ccfile_service_proxy_func}}", ccfile_service_proxy_func) \
                    .replace("{{service_name}}", service_name)
                ccfile_service_proxy_class += ccfile_one_service_proxy_class

            # hfile
            hfile: CodeGeneratorResponse.File = CodeGeneratorResponse.File()
            hfile.name = h_file_name
            hfile.content = self.t_hfile \
                .replace("{{hfile_service_class}}", hfile_service_class) \
                .replace("{{hfile_service_proxy_class}}", hfile_service_proxy_class) \
                .replace("{{file_name}}", file_name.replace('.proto', '')) \
                .replace("{{namespace_begin}}", namespace_begin) \
                .replace("{{namespace_end}}", namespace_end) \
                .replace("{{package_name}}", package_name)
            response.file.append(hfile)

            # ccfile
            ccfile: CodeGeneratorResponse.File = CodeGeneratorResponse.File()
            ccfile.name = cc_file_name
            ccfile.content = self.t_ccfile \
                .replace("{{ccfile_service_class}}", ccfile_service_class) \
                .replace("{{ccfile_service_proxy_class}}", ccfile_service_proxy_class) \
                .replace("{{file_name}}", file_name.replace('.proto', '')) \
                .replace("{{namespace_begin}}", namespace_begin) \
                .replace("{{namespace_end}}", namespace_end) \
                .replace("{{package_name}}", package_name)
            response.file.append(ccfile)

        return response


if __name__ == '__main__':
    # Load the request from stdin
    request: CodeGeneratorRequest = CodeGeneratorRequest.FromString(sys.stdin.buffer.read())

    aimrt_code_generator: AimRTCodeGenerator = AimRTCodeGenerator()

    response: CodeGeneratorResponse = aimrt_code_generator.generate(request)

    # Serialize response and write to stdout
    sys.stdout.buffer.write(response.SerializeToString())
