name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test-linux-gcc:
    uses: ./.github/workflows/test.yml
    with:
      run_platform: ${{ matrix.platform }}
      image_name: ${{ matrix.image }}
      tool_chain: ${{ matrix.tool_chain }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            tool_chain: gcc-11
            image: ros:humble-ros-core-jammy
          - platform: ubuntu-22.04-arm
            tool_chain: gcc-11
            image: ros:humble-ros-core-jammy
